apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: search
  namespace: production
spec:
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
      - name: ori-search
        args:
        - /usr/src/app/server.js
        command:
        - node
        image: argu/ori-search
        imagePullPolicy: Always
        env:
        - name: SEARCH_GLOSS_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: SEARCH_GLOSS_CLIENT_ID
              name: secrets
        - name: SEARCH_GLOSS_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: SEARCH_GLOSS_CLIENT_SECRET
              name: secrets
        resources:
          requests:
            memory: 30Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: DoesNotExist
