version: "2.1"
services:
  backend:
    image: openstatefoundation/open-raadsinformatie-backend
    links:
      - redis:redis
      - elastic_endpoint:elasticsearch
      - frontend:frontend
    ports:
      - "81:5555"
    volumes:
      - oridata:/opt/ori/data
    depends_on:
      elastic_endpoint:
        condition: service_healthy
    mem_limit: 3g
    restart: always
  frontend:
    image: openstatefoundation/open-raadsinformatie-frontend
    links:
      - elastic_endpoint:elasticsearch
    depends_on:
      elastic_endpoint:
        condition: service_healthy
    ports:
      - "5000:5000"
    restart: always
  redis:
    image: "redis:${REDIS_VERSION}"
    volumes:
     - redisdata:/data
    sysctls:
     - net.core.somaxconn=65535
    mem_limit: 8g
    restart: always
    command: redis-server --appendonly yes --save ''
  elastic_endpoint:
    container_name: ori_elastic_endpoint
    extends:
      service: elastic
    ports:
      - "9200:9200"
    environment:
      - http.host=0.0.0.0
      - node.master=true
    restart: always
  elastic:
    image: "docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}"
    environment:
      - network.host=0.0.0.0
      - discovery.zen.ping.unicast.hosts=ori_elastic_endpoint
      - discovery.zen.minimum_master_nodes=2
      - node.max_local_storage_nodes=20
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: wget -q -O - http://127.0.0.1:9200/_cat/health
      interval: 15s
      timeout: 10s
      retries: 3
    restart: always
volumes:
  esdata:
    driver: local
  redisdata:
    driver: local
  oridata:
    driver: local
